=== mariananietodaw/LM_EjerciciosXSD/expresiones-regulares.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="expresiones-regulares">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="expresiones" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="expresion1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Capítulo \d"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion2">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Capítulo \d\d?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion3">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Capítulo [1-9]\d?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion4">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Capítulo \d+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion5">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\DZ"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion6">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="AB{2,5}C"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion7">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="RSS+[3-8]?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="expresion8">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="COD\d{3}.+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mariananietodaw/LM_EjerciciosXSD/expresiones-regulares.xml
<?xml version="1.0" encoding="UTF-8"?>
<expresiones-regulares xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="expresiones-regulares.xsd">
    <expresiones>
        <expresion1>Capítulo 0</expresion1>
        <expresion2>Capítulo 0</expresion2>
        <expresion3>Capítulo 1</expresion3>
        <expresion4>Capítulo 0</expresion4>
        <expresion5>aZ</expresion5>
        <expresion6>ABBC</expresion6>
        <expresion7>RSS</expresion7>
        <expresion8>COD645pera</expresion8>
    </expresiones> 
    <expresiones>
        <expresion1>Capítulo 9</expresion1>
        <expresion2>Capítulo 99</expresion2>
        <expresion3>Capítulo 99</expresion3>
        <expresion4>Capítulo 99999</expresion4>
        <expresion5>?Z</expresion5>
        <expresion6>ABBBBBC</expresion6>
        <expresion7>RSSSSSSSSSSS7</expresion7>
        <expresion8>COD646manzana</expresion8>
    </expresiones>
</expresiones-regulares>
