=== mariananietodaw/LM_EjerciciosXSD/FICHAS3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="FICHA3">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="ficha" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nombre" type="xs:string"/>
                                <xs:element name="iniciales" type="tresLetras"/>
                                <xs:element name="edad" type="xs:integer"/>
                                <xs:element name="iniciales-al-reves" type="tresLetras"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        
        <xs:simpleType name="tresLetras">
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z][A-Z][A-Z]"/>
            </xs:restriction>
        </xs:simpleType>
        
</xs:schema>

=== mariananietodaw/LM_EjerciciosXSD/FICHAS3.xml
<?xml version="1.0" encoding="UTF-8"?>
<FICHA3 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FICHAS3.xsd">
    <ficha>
        <nombre>Ana Sanz Tin</nombre>
        <iniciales>AST</iniciales>
        <edad>22</edad>
        <iniciales-al-reves>TSA</iniciales-al-reves>
    </ficha>
    <ficha>
        <nombre>Iker Rubio Mol</nombre>
        <iniciales>IRM</iniciales>
        <edad>23</edad>
        <iniciales-al-reves>MRI</iniciales-al-reves>
    </ficha>
</FICHA3>
